"""add

Revision ID: 20a17533e29d
Revises: 
Create Date: 2019-12-11 15:29:46.769617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a17533e29d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Services')
    op.drop_table('Codif_of_proficiency_lang')
    op.drop_table('Trustee')
    op.drop_table('Codif_of_language')
    op.drop_table('Employees')
    op.drop_table('Natural_Persons')
    op.drop_table('Legal_Persons')
    op.drop_table('Countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Countries',
    sa.Column('code_of_country', sa.INTEGER(), server_default=sa.text('nextval(\'"Countries_code_of_country_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name_of_country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code_of_country', name='Countries_pkey')
    )
    op.create_table('Legal_Persons',
    sa.Column('code_of_client', sa.INTEGER(), server_default=sa.text('nextval(\'"Legal_Persons_code_of_client_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name_of_client', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code_of_client', name='Legal_Persons_pkey')
    )
    op.create_table('Natural_Persons',
    sa.Column('code_of_client', sa.INTEGER(), server_default=sa.text('nextval(\'"Natural_Persons_code_of_client_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('farther_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('sex', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_of_marriage', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('code_of_client', name='Natural_Persons_pkey')
    )
    op.create_table('Employees',
    sa.Column('code_of_employee', sa.INTEGER(), server_default=sa.text('nextval(\'"Employees_code_of_employee_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('farther_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('sex', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('type_of_employee', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_of_licence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_of_lic_issuance', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('code_of_employee', name='Employees_pkey')
    )
    op.create_table('Codif_of_language',
    sa.Column('code_of_lang', sa.INTEGER(), server_default=sa.text('nextval(\'"Codif_of_language_code_of_lang_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name_of_lang', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code_of_lang', name='Codif_of_language_pkey')
    )
    op.create_table('Trustee',
    sa.Column('num_and_ser_of_doc', sa.INTEGER(), server_default=sa.text('nextval(\'"Trustee_num_and_ser_of_doc_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('date_of_regist_of_trust', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('place_of_regist_of_trust', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('num_and_ser_of_doc', name='Trustee_pkey')
    )
    op.create_table('Codif_of_proficiency_lang',
    sa.Column('code_of_profic', sa.INTEGER(), server_default=sa.text('nextval(\'"Codif_of_proficiency_lang_code_of_profic_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name_of_profic', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code_of_profic', name='Codif_of_proficiency_lang_pkey')
    )
    op.create_table('Services',
    sa.Column('code_of_service', sa.INTEGER(), server_default=sa.text('nextval(\'"Services_code_of_service_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('addition_docum', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('code_of_service', name='Services_pkey'),
    sa.UniqueConstraint('name', name='Services_name_key')
    )
    # ### end Alembic commands ###
