"""empty message

Revision ID: 6d840982d507
Revises: ed3d5e422335
Create Date: 2019-12-02 15:41:42.566862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d840982d507'
down_revision = 'ed3d5e422335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('бла')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('бла',
    sa.Column('код', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('имя', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('код', name='бла_pkey')
    )
    # ### end Alembic commands ###
