"""empty message

Revision ID: a9b470b2cf40
Revises: 6d840982d507
Create Date: 2019-12-02 17:32:14.814814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b470b2cf40'
down_revision = '6d840982d507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Бланки',
    sa.Column('num_of_form', sa.Integer(), nullable=False),
    sa.Column('type_of_form', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('num_of_form', 'type_of_form')
    )
    op.create_table('Доверенное лицо',
    sa.Column('num_of_doc', sa.Integer(), nullable=False),
    sa.Column('series_of_doc', sa.Integer(), nullable=False),
    sa.Column('date_of_regist_of_trust', sa.DATE(), nullable=True),
    sa.Column('place_of_regist_of_trust', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('num_of_doc', 'series_of_doc')
    )
    op.create_table('Док-т клиента',
    sa.Column('number_of_doc', sa.Integer(), nullable=False),
    sa.Column('series_of_doc', sa.Integer(), nullable=False),
    sa.Column('code_of_client', sa.Integer(), nullable=True),
    sa.Column('name_of_doc', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('number_of_doc', 'series_of_doc')
    )
    op.create_table('Журнал регистрации',
    sa.Column('date_of_issuance', sa.DATE(), nullable=True),
    sa.Column('num_of_act', sa.Integer(), nullable=False),
    sa.Column('code_of_client', sa.Integer(), nullable=True),
    sa.Column('code_of_service', sa.Integer(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('num_of_act')
    )
    op.create_table('Заявка',
    sa.Column('num_of_applic', sa.Integer(), nullable=False),
    sa.Column('code_of_employee', sa.Integer(), nullable=True),
    sa.Column('code_of_service', sa.Integer(), nullable=True),
    sa.Column('date_of_record', sa.DATE(), nullable=True),
    sa.Column('series_of_docum', sa.Integer(), nullable=True),
    sa.Column('number_of_docum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('num_of_applic')
    )
    op.create_table('Знание ин-го языка',
    sa.Column('code_of_lang', sa.Integer(), nullable=False),
    sa.Column('code_of_empl', sa.Integer(), nullable=False),
    sa.Column('code_of_knowl', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('code_of_lang', 'code_of_empl')
    )
    op.create_table('Клиент',
    sa.Column('code_of_client', sa.Integer(), nullable=False),
    sa.Column('code_of_type_of_client', sa.Integer(), nullable=True),
    sa.Column('code_of_country', sa.Integer(), nullable=True),
    sa.Column('e_mail', sa.VARCHAR(length=30), nullable=True),
    sa.Column('address', sa.VARCHAR(length=80), nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('code_of_client')
    )
    op.create_table('Код-р ин-го языка',
    sa.Column('code_of_lang', sa.Integer(), nullable=False),
    sa.Column('name_of_lang', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('code_of_lang')
    )
    op.create_table('Код-р степени знания ин-го языка',
    sa.Column('code_of_profic', sa.Integer(), nullable=False),
    sa.Column('name_of_profic', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('code_of_profic')
    )
    op.create_table('Сотрудник',
    sa.Column('code_of_employee', sa.Integer(), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('farther_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('address', sa.VARCHAR(length=80), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('type_of_employee', sa.VARCHAR(), nullable=True),
    sa.Column('number_of_licence', sa.Integer(), nullable=True),
    sa.Column('date_of_lic_issuance', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('code_of_employee')
    )
    op.create_table('Страна',
    sa.Column('code_of_country', sa.Integer(), nullable=False),
    sa.Column('name_of_country', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code_of_country')
    )
    op.create_table('Услуга',
    sa.Column('code_of_service', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('addition_docum', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('code_of_service')
    )
    op.create_table('Участники',
    sa.Column('series_of_doc', sa.Integer(), nullable=False),
    sa.Column('num_of_doc', sa.Integer(), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('farther_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('series_of_doc', 'num_of_doc')
    )
    op.create_table('Физическое лицо',
    sa.Column('code_of_client', sa.Integer(), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('farther_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('data_of_marriage', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('code_of_client')
    )
    op.create_table('Юридическое лицо',
    sa.Column('code_of_client', sa.Integer(), nullable=False),
    sa.Column('name_of_client', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('code_of_client')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Юридическое лицо')
    op.drop_table('Физическое лицо')
    op.drop_table('Участники')
    op.drop_table('Услуга')
    op.drop_table('Страна')
    op.drop_table('Сотрудник')
    op.drop_table('Код-р степени знания ин-го языка')
    op.drop_table('Код-р ин-го языка')
    op.drop_table('Клиент')
    op.drop_table('Знание ин-го языка')
    op.drop_table('Заявка')
    op.drop_table('Журнал регистрации')
    op.drop_table('Док-т клиента')
    op.drop_table('Доверенное лицо')
    op.drop_table('Бланки')
    # ### end Alembic commands ###
