"""empty message

Revision ID: ed3d5e422335
Revises: 9cd149567dd4
Create Date: 2019-12-02 15:34:04.135590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3d5e422335'
down_revision = '9cd149567dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('бла')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('бла',
    sa.Column('код', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('код', name='бла_pkey')
    )
    # ### end Alembic commands ###
